### ISSUE TITLE
Structural difference?

### ISSUE THREAD

**Issue by DonMathi** [andrew-gresyk/HFSM2#10]
Hi Andrew

Is there an structural difference between
`M::Root<THead, TStates>`
and 
`M::PeerRoot<M::Composite<THead, TStates>>`
and
`M::PeerRoot<THead,M::CompositePeers<TStates>>`

Does all 3 implementation give the same?
Which is better?

**Comment by andrew-gresyk** [comment]
Hi Kjeld,

'Peer' variants are typedefs for headless regions/roots:

```M::PeerRoot<TStates...>``` is equivalent to ```M::Root<Empty, TStates...>```
```M::CompositePeers<TStates...>``` is equivalent to ```M::Composite<Empty, TStates...>```

Roots are regions themselves, and don't require extra regions to function as one.

```M::Root<THead, TStates...>``` is a general case composite root with a head state.

```M::PeerRoot<M::Composite<THead, TStates>>``` is a headless root with one child (which is probably not what you want):

```
M::Root<Empty>
└ M::Composite<THead>
  ├  TState1
  └  TState2
```

```M::PeerRoot<THead,M::CompositePeers<TStates>>``` is a headless root with two children (which is probably not what you want either):

```
M::Root<Empty>
├ THead
└ M::Composite<Empty>
  ├  TState1
  └  TState2
```

**Comment by DonMathi** [comment]
Thank you
