### ISSUE TITLE
"Fully static, no dynamic allocations" but "new" used several times

### ISSUE THREAD

**Issue by microtronics** [andrew-gresyk/HFSM2#104]
Hi!
Maybe this is a stupid question, but I stumbled across this during debugging for an ARM cortex-M target:
This library is meant to be fully static with no dynamic allocations, but the keyword "new" is used at several locations:

```
template <typename T, Long NC_>
template <typename... TArgs>
HFSM2_CONSTEXPR(14)
typename DynamicArrayT<T, NC_>::Index
DynamicArrayT<T, NC_>::emplace(const TArgs&... args) noexcept {
	HFSM2_ASSERT(_count < CAPACITY);

	new (&_items[_count]) Item{args...};

	return _count++;
}
```

Isn't that dynamic allocation? It seems like on my target there is actual heap allocation at these points. What am I missing?

**Comment by andrew-gresyk** [comment]
Hi,
It's [placement new](https://en.cppreference.com/w/cpp/language/new#Placement_new).

**Comment by microtronics** [comment]
Wow, thanks for the quick reply.
The reuse of keywords in C++ will kill me one day. It will probably kill C++, too...
Thanks for enlightening me!
