### ISSUE TITLE
Orthogonal Regions with Composite

### ISSUE THREAD

**Issue by DonMathi** [andrew-gresyk/HFSM2#12]
Hi Andrew

I'm having some problems with creating orthogonal regions with composite parts.
I have something like this:

```
struct SomeEvent{};
HFSM=Machine::Root<A,
    B,
    Machine::Orthogonal<C,
        Machine::Composite<D,
            E,F,G,Machine::Composite<H,I,J>
        >,
        Machine::Composite<K,
            L,
            Machine::Composite<M,N,O>,
            Machine::Composite<P,Q,R>,
            Machine::Composite<S,T,U>,
            V
        >
    >,
    W
>;
```

The structure compiles fine, but when I add changeTo to state E, then it complains
```
state E : HFSM::State
{
    void react(const SomeEvent&, FullControl& control)
    {
        control.changeTo<F>();
    }
    using HFSM::State::react;
}
```

**Comment by DonMathi** [comment]
It points to line 577, and says mo matching candidates for
`void* operator new(long unsigned int)`

**Comment by DonMathi** [comment]
The IDE tells me that all states from K to W are unused. (Grayed out)

**Comment by DonMathi** [comment]
I think I will just create 2 separate HFSM to handle each region inside my class for now.

**Comment by andrew-gresyk** [comment]
Hi Kjeld,
Let me check

**Comment by andrew-gresyk** [comment]
Do you have a complete example I can test?

**Comment by DonMathi** [comment]
[HFSM_TEST.zip](https://github.com/andrew-gresyk/HFSM2/files/4192801/HFSM_TEST.zip)

**Comment by DonMathi** [comment]
Hope it works

**Comment by DonMathi** [comment]
Found a small bug

**Comment by DonMathi** [comment]
[StateMachine.zip](https://github.com/andrew-gresyk/HFSM2/files/4192814/StateMachine.zip)

**Comment by andrew-gresyk** [comment]
Ah, I see.

For ```control.changeTo<StateE>();``` to work, transition target state ```StateE``` needs to be either forward declared, or fully defined before the call.

In this case, moving the body of ```StateD::react<>()``` below the definition of ```StateE```

This works for me:
```cpp
// ..
class StateMachine
{
	// ..
	struct StateD: HFSM::State
	{
		using HFSM::State::react;

		void react(const SomeEvent&, FullControl& control);
	};

	struct StateE: HFSM::State { using HFSM::State::react; };
	// ..
};

void StateMachine::StateD::react(const SomeEvent&, FullControl& control)
{
	control.changeTo<StateE>();
}
// ..
```

**Comment by DonMathi** [comment]
ahhh, It is because I have everything in the *.h file

**Comment by DonMathi** [comment]
Thank you for your quick reply

**Comment by DonMathi** [comment]
However it seems like that after a Composite inside a Orthogonal it stops taking more states?

**Comment by andrew-gresyk** [comment]
Does it compile after you swap them?

**Comment by DonMathi** [comment]
No I still have problems with getting the control.changeTo to work

**Comment by DonMathi** [comment]
And half of the structs are grayed-out (not used).
I'll talk to you again to morrow, have to go now

**Comment by andrew-gresyk** [comment]
Actually, your original example with un-commented line seems to work for me, in VS 16.4.5 and Clang 9.0 and in GCC 9.1

Can you test that machine in a separate .cpp?

**Comment by DonMathi** [comment]
Hi Andrew
I think I found the error. It had nothing to do with hfsm2.
Somehow I had to include a common project file, that included other system libs.
Now it works

**Comment by andrew-gresyk** [comment]
Great.
I noticed you were using empty context in you example.
In that case you can also use another constructor that doesn't require context argument:

```hfsm2::Machine;``` vs ```hfsm2::MachineT<Context>;```

**Comment by DonMathi** [comment]
It's only empty for now
