### ISSUE TITLE
Hitting the CAPACITY roof

### ISSUE THREAD

**Issue by DonMathi** [andrew-gresyk/HFSM2#13]
Hi Andrew

Next quest for you. My state machine has become so large that it complains about (line 1013)
`static_assert(UNIT+(WIDTH+7)/(sizeof(Unit)*8)<=CAPACITY,"");`

How do I change the CAPACITY limit?

**Comment by DonMathi** [comment]
I have somthing like this: M=Machine, H=Head, S=State, O=Orthogonal, C=Composite
```
M(H,
S,
O[H,
    C{H,
    S,
    S,
    O[H,
        C{H,S,S},
        C{H,S,S,S}
    ]
    },
    C{H,
        S,
        C{H,S,S},
        C{H,S,S},
        C{H,S,S},
        S
    }
],
S
)
```

**Comment by andrew-gresyk** [comment]
Hi Kjeld,
Looks like a bug, looking into that.

**Comment by andrew-gresyk** [comment]
Fixed in [Beta 7.3](../releases/tag/Beta73)

**Comment by DonMathi** [comment]
Great

**Comment by DonMathi** [comment]
I still had some issues, but now I also #include <memory>, this helps.
Do you require some extra libs, that are not included in your machine.hpp file?

**Comment by andrew-gresyk** [comment]
Nope, HFSM doesn't have any other dependencies.
Are you saying you needed to ```#include <memory>``` to fix an HFSM2 build issue?

**Comment by DonMathi** [comment]
Yes. Without it complains about `new` for many different things inside hfsm2.
Maybe `#include <memory>` is not the direct needed dependency, but it solves the problem

**Comment by andrew-gresyk** [comment]
Do you have an example I can look at?
Also, which compiler are you on?

**Comment by DonMathi** [comment]
MinGW64 version 8.1.0
Issue at line 577 in your machine.hpp 
`error: no matching function for call to 'operator new(sizetype, hfsm2::detail::Array<hfsm2::detail::RequestT<hfsm2::EmptyPayload>, 8>::Item*)'
  new (&_items[_count]) Item{std::move(value)};
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by andrew-gresyk** [comment]
Interesting.
Do any of the bundled examples compile on your platform?

**Comment by andrew-gresyk** [comment]
Added ```#include <new>``` for all platforms.
Let me know if this fixes the issue.

**Comment by DonMathi** [comment]
Yes, that solves the issue
