### ISSUE TITLE
Reacting to events deeply

### ISSUE THREAD

**Issue by jfflak** [andrew-gresyk/HFSM2#14]
Hi, I have a scenario where I am transitioning into a state (`FHaveTarget`) because of a parent state's `react()` function. In `FHaveTarget::entryGuard()`, I want to set the initial substate of `FHaveTarget` based on the parameters from that event.

Is there a way for the parent to pass those parameters into the `entryGuard()` of the state? Here follows the simplest version of this I've got.

The two ways I can think around this are to add parameters to a shared context object, or to flatten the hierarchy, neither of which are satisfactory.

How should I do this in HFSM2?

```
using M = hfsm2::Machine
using FSM =
	M::Root
	<
		struct FRoot,
		struct FNoTarget,
		M::Composite
		<
			struct FHaveTarget,
			struct FTargetInRange,
			struct FTargetOutOfRange
		>
	>;

struct FUpdateTargetEvent
{
	AActor* Target;
	bool    bTargetOutOfRange;
};

struct FRoot : FSM::State
{
	void react(FUpdateTargetEvent const& Event, FullControl& Control)
	{
		if (Event.Target)
		{
			Control.changeTo<FHaveTarget>();
		}
		else
		{
			Control.changeTo<FNoTarget>();
		}
	}
};

struct FNoTarget : FSM::State
{
};

struct FHaveTarget : FSM::State
{
	void entryGuard(FullControl& control)
	{
		// HERE is where I don't have the data I want: Event
		if (Event.bTargetOutOfRange)
		{
			Control.changeTo<FTargetOutOfRange>();
		}
		else
		{
			Control.changeTo<FTargetInRange>();
		}
	}

	void enter(Control& control) { /* set FireTarget (somehow) and set some state on it */ }
	void exit(Control& control)  { /* unset that state */ }

private:
	AActor* FireTarget = nullptr;
};

struct FTargetInRange : FSM::State
{
	void enter(Control& control) { /* set some additional state on target */ }
	void exit(Control& control) { /* unset that state */ }
};

struct FTargetOutOfRange : FSM::State
{
};
```

**Comment by andrew-gresyk** [comment]
Release [1.1](../releases/tag/1_1) adds `FSM::Instance::access<TState>()`.

It is only available on the FSM::Instance, and not on `*Control`.

If you pass the reference to your `AActor` using `TContext` to the instance of your FSM, you can then use `TState& access<TState>()` to set the value of `FHaveTarget::FireTarget` and initiate the transition to that region:

```cpp
struct FRoot : FSM::State
{
	void react(FUpdateTargetEvent const& Event, FullControl& Control)
	{
		if (Event.Target)
		{
			Control.context().access<FHaveTarget>().FireTarget = Event.Target;
			Control.changeTo<FHaveTarget>();
		}
		else
		{
			Control.changeTo<FNoTarget>();
		}
	}
};
```

**Comment by jfflak** [comment]
Yes, this allows me to do what I want. Although, after our discussion on twitter, I went with the context setting and update() pattern like so:

```
void FRoot::update(FullControl& Control)
{
	if (Control.context().CurrentTarget)
	{
		if (Control.context().CurrentTarget != Control.context().Owner->TargetingFSM->access<FHaveTarget>().Target)
		{
			Control.restart<FHaveTarget>();
		}
	}
	else
	{
		Control.changeTo<FNoTarget>();
	}
}
```

Thank you!
