### ISSUE TITLE
Compile error in B_<TFirst>::stateId()

### ISSUE THREAD

**Issue by jfflak** [andrew-gresyk/HFSM2#15]
The following, in clang

```
MyState : FSM::State
{
	void update(FullControl& control)
	{
		hfsm2::StateID OtherStateID = stateId<MyOtherState>();

		// do some stuff
	}
}
```

Gives this error (in machine.hpp~4395):

```
error : template name refers to non-type template 'index'
1>          static constexpr StateID  stateId()                             { return                        typename TFirst::StateList ::template index<T>();       }
```

I believe the compiler is treating the `typename` keyword as though it applies to the whole function call expression (`TFirst::StateList:: template index<T>()`) instead of just `TFirst::StateList`.

I tried to disambiguate this inline by finding the right incantation of typename/template keywords, but it proved beyond my capabilities.

This fixed the error:

```
	using StateList = typename TFirst::StateList;

	template <typename T>
	static constexpr StateID  stateId()				{ return			StateList ::template index<T>();	}
```

**Comment by andrew-gresyk** [comment]
Thanks for the heads up, I'll have a look.

**Comment by andrew-gresyk** [comment]
[1.1.1](../releases/tag/1_1_1) should fix that.

**Comment by jfflak** [comment]
Confirmed, thank you.
