### ISSUE TITLE
The logger can freeze due to unknown methods

### ISSUE THREAD

**Issue by AlexisTM** [andrew-gresyk/HFSM2#16]
The following snippet is missing `CONSTRUCT` and `DESTRUCT`. In which case it returns nullptr. Yet, these functions seem to be called when we implement enter and exit functions.

https://github.com/andrew-gresyk/HFSM2/blob/d1674dfcaa68b98c130a83528d6f13eac4230a5c/include/hfsm2/detail/debug/shared.hpp#L73-L92

This causes the proposed "recordMethod" logger to be stuck:

```cpp
  void recordMethod(Context& /*context*/, const StateID origin, const Method method) override {
    std::cout << stateName(origin) << "::" << hfsm2::methodName(method) << "()" << std::endl;
  }
```

Adding the two fixes the freeze and we have the following output:

```
Idle -> DoAction
DoAction::contruct()
DoAction::enter()
HeadState::update()
HeadState -> Idle
DoAction::update()
DoAction -> Idle
DoAction::exit()
DoAction::destruct()
HeadState::update()
```

This function should not return nullptr but instead `'\0'` or `unknownMethod` to prevent unsafe operations.

**Comment by andrew-gresyk** [comment]
Thanks for reporting, Alexis, I'll look into it.

**Comment by andrew-gresyk** [comment]
Should be fixed in [1.2.2](../releases/tag/1_2_2)

**Comment by AlexisTM** [comment]
I don't think it should return nullptr as examples of the logger stream the output to std::cout with no nullptr check on the data.

**Comment by AlexisTM** [comment]
In the meantime, this freeze should not happen as all methods are caught. :)

**Comment by andrew-gresyk** [comment]
There are several reasons why I prefer the return on failure to be `nullptr`:
0. it's a standard failing return value
1. checking against `0` is the fastest check, typically implemented with `test eax, eax` without the use of any other registers or values
2. I'd rather the program crashed on error, than silently producing invalid output
3. if it did return "\0", checking for it required a pointer dereference, most likely a cache miss
