### ISSUE TITLE
Can't get Context from Control in Utility function

### ISSUE THREAD

**Issue by tastesliketriangle** [andrew-gresyk/HFSM2#25]
I have tried to get a variable from the current Context to modify the Utility function. this doesn't seem to work for me. leaving the Control signature const results in the following error in intellisense:

`C++ the object has type qualifiers that are not compatible with the member function            object type is: const hfsm2::detail::ControlT<hfsm2::detail::ArgsT<Context, hfsm2::detail::G_<(hfsm2::FeatureTag)'\001', Context, int8_t, float, hfsm2::RandomT<float>, (hfsm2::Long)4U, void>, hfsm2::detail::Merge<hfsm2::detail::ITL_<void>, hfsm2::detail::Merge<hfsm2::detail::Merge<hfsm2::detail::ITL_<Red>, hfsm2::detail::Merge<hfsm2::detail::ITL_<Yellow>, hfsm2::detail::ITL_<Green>>>, hfsm2::detail::ITL_<Off>>>, hfsm2::detail::Merge<hfsm2::detail::ITL_<void>, hfsm2::detail::Merge<hfsm2::detail::ITL_<Red>, hfsm2::detail::Merge<hfsm2::detail::ITL_<>, hfsm2::detail::ITL_<>>>>, (hfsm2::Long)2U, (hfsm2::Long)0U, (hfsm2::Long)0U, (hfsm2::Long)6U, (hfsm2::Long)4U, void>>`

Removing the cosnt gets rid of the error, but causes compilation to fail.

I made a minimal example to test the error, and it still seems to happen.

```CPP
#define HFSM2_ENABLE_UTILITY_THEORY
#include <hfsm2/machine.hpp>
#include <iostream>

struct Context {
	uint8_t cycleCount = 0;
};

using M = hfsm2::MachineT<hfsm2::Config::ContextT<Context>>;

#define S(s) struct s
using FSM = M::PeerRoot<
	M::Utilitarian<S(Red),
	S(Yellow),
	S(Green)
	>,
	S(Off)
>;
#undef S

struct On
	: FSM::State {
	void enter(Control& control) {
		control.context().cycleCount = 0;
		std::cout << "On" << std::endl;
	}};

struct Red
	: FSM::State {
	void enter(Control& control) {
		++control.context().cycleCount;
		std::cout << "  Red" << std::endl;
	}

	void update(FullControl& control) {
		if (control.context().cycleCount > 3)
			control.changeTo<Off>();
		else
			control.changeTo<Green>();
	}};

struct Yellow
	: FSM::State {
	void enter(Control&) { std::cout << "    Yellow ^" << std::endl; }
	void update(FullControl& control) { control.changeTo<Red>(); }
	///
	Utility utility(const Control& control) { return 0.5f + control.context().cycleCount; }
	///
};

struct Green
	: FSM::State {
	void enter(Control&) { std::cout << "      Green" << std::endl; }
	void update(FullControl& control) { control.changeTo<Yellow>(); }
};

struct Off
	: FSM::State {
	void enter(Control&) { std::cout << "Off" << std::endl; }
};

int main() {
	Context context;
	FSM::Instance machine{ context };

	while (machine.isActive<Off>() == false)
		machine.update();

	return 0;
}
```

**Comment by andrew-gresyk** [comment]
Thanks for reporting!
Fixed in https://github.com/andrew-gresyk/HFSM2/releases/tag/1_7_1

**Comment by tastesliketriangle** [comment]
That seems to have fixed it, thanks!
