### ISSUE TITLE
Examples for HFSM2

### ISSUE THREAD

**Issue by DJuego** [andrew-gresyk/HFSM2#4]
Thank you for this promising contribution, @andrew-gresyk! I like very much little header-only gems like this library! :-D

I am a absolute newbie in Hierarchical Finite State Machines. :-) My interests are robotics and games too.

However i am interested in knowing more about it. I would like to familiarize myself with some kind of (graphical?) representation of HFSM.  Any suggestion? Any recommended reading?

I miss a series of examples that serve to show/explain the library and, incidentally, to test it. :-)

Cheers!

DJuego

**Comment by andrew-gresyk** [comment]
Glad you like it!

As for the examples - have you seen the [HFSM2 examples](https://github.com/andrew-gresyk/HFSM2/tree/master/examples) ?
[HFSM2 tests](https://github.com/andrew-gresyk/HFSM2/tree/master/test) might also clear up how the transitions in the hierarchy are expected to work.

For the general quick intro into HFSMs - see [The Gist of Hierarchical FSM by Alex J. Champandard](http://aigamedev.com/open/article/hfsm-gist/).

In my experience, there's not a unified way to think about HFSM, everyone tends to reinvent their own, so the material "on HFSM" from different sources varies greatly.

Many FSM implementations are very simplistic, and suffer from the common problem of decision logic being spread all over the FSM code (see [Dave Mark's AI Architectures: A Culinary Guide](http://intrinsicalgorithm.com/IAonAI/2012/11/ai-architectures-a-culinary-guide-gdmag-article/) for details, scroll down to *A Softer Approach—The Behavior Tree*).

This library aims to solve this problem by allowing regions (sub-state machines within a hierarchy) to have decision logic, either with ```entryGuard()``` method, or using utility-based selector with ```Utilitarian``` region or ```utilize<TRegion>()``` transition.

Gamedev FSM links:
* [The Total Beginner's Guide to Game AI](https://www.gamedev.net/articles/programming/artificial-intelligence/the-total-beginners-guide-to-game-ai-r4942/) by Ben Sizer
* [Game AI Pro 3](http://www.gameaipro.com/) has 2 articles (11 and 12) on FSM architecture.
* [DOOM 2016](https://aiandgames.com/doom2016/) and [Arkham Asylum](https://aiandgames.com/arkham-intelligence/) videos by Tommy Thompson

Non-gamedev FSM links:
* [UML State Machine Diagram Examples](https://www.uml-diagrams.org/state-machine-diagrams-examples.html)
* Boost [statechart](https://www.boost.org/doc/libs/1_70_0/libs/statechart/doc/tutorial.html) and [MSM](https://www.boost.org/doc/libs/1_45_0/libs/msm/doc/HTML/ch03.html)

Also, if you're into game AI, check out the competing solutions to HFSMs:
* Behaviour Trees
* Hierarchical Task Networks
* Planners (e.g. GOAP)
* Utility Theory

My goal with HFSM2 is to incorporate useful ideas from all of them to create a hybrid solution covering more potential applications, and you can find traces of the above in HFSM2.

**Comment by DJuego** [comment]
Fantastic answer! Thanks!  I hope to test your vision! :-)

And thank you for the links! I missed the HFSM2 examples. My bad.

DJuego
