### ISSUE TITLE
Usage within ecs systems like entt

### ISSUE THREAD

**Issue by kariem2k** [andrew-gresyk/HFSM2#43]
Thank you very much for the library, it is one of the most robust libraries I found in Github. I am thinking of employing it within entt ecs framework. Do you have any recommendations or experience? Do I store FSM::Instance (FSM is M::Root or M::PeerRoot) as a component in the ecs system? Is the size of the FSM::Instance always constant regardless of the state selected if the plan did not change (ie it has the size of the largest state?)

Thanks

**Comment by kariem2k** [comment]
I think I need to disable plans to achieve the constant compile-time deterministic size of the machine.

**Comment by andrew-gresyk** [comment]
Thank you Karim!
The size of `FSM::Instance` is always constant, there are no dynamic allocations made ever.
It's constant **but** will differ depending on the features you have enabled.
