### ISSUE TITLE
Using in embedded systems

### ISSUE THREAD

**Issue by SergeTauger** [andrew-gresyk/HFSM2#44]
I'd like use HFSM2 in firmware for stm32, compiler is GNU ARM Embedded Toolchain (gcc 10.2 or 9.3.1). The problem is that both RTOSes and bare metal usually don't support stdlib and POSIX. Can I use the library as it is or some efforts to port are needed?

**Comment by andrew-gresyk** [comment]
Never tried that.
Give it a go!

**Comment by SergeTauger** [comment]
I cannot get how event dispatching is done.  Is that right that std::thread is not used and we should call update() in infinite loop? And I cannot find any usages of mutexes/semaphores in the code, so I have no idea how you implemented event queue. Could you please point me to the code that does dispatching?

**Comment by andrew-gresyk** [comment]
`std::thread` isn't used.
You should call `update()` in a loop after `changeTo<>()`
Or just call `handleEvent()`

There is no event queue, it's outside the scope of an FSM library
So is multithreading support
