### ISSUE TITLE
Port travis to Github Actions

### ISSUE THREAD

**Issue by fire** [andrew-gresyk/HFSM2#46]
https://github.com/andrew-gresyk/HFSM2/blob/master/.travis.yml

Placeholder.

**Comment by fire** [comment]
@andrew-gresyk Out of all the platforms which Linux one do you want to start?

**Comment by andrew-gresyk** [comment]
@fire No strong preference TBH.

**Comment by fire** [comment]
I'm pausing because I want to take a vacation, so I'll close for now. However, if I wake up one day ready..
