### ISSUE TITLE
Macro conflict between sys/ioctl.h and hfsm2/machine.hpp

### ISSUE THREAD

**Issue by spiderkeys** [andrew-gresyk/HFSM2#63]
I discovered today that there appears to be a conflict between HFSM2 and the Linux libc sys/ioctl.h header that causes a bizarre cascade of template errors and syntax errors. 

The conflict occurs when including sys/ioctl.h before hfsm2/machine.hpp, due to HFSM2's use of the symbol `NCC` in various template arguments in machine.hpp:
https://github.com/andrew-gresyk/HFSM2/blob/master/include/hfsm2/machine.hpp#L3562

`NCC` is defined as an integer literal in <bits/ioctl-types.h> which gets included by <sys/ioctl.h>:
https://github.com/raspberrypi/tools/blob/master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/libc/usr/include/arm-linux-gnueabihf/bits/ioctl-types.h#L36

After renaming `NCC` to `_NCC` in HFSM2, I can confirm that the errors are resolved.

It's a bit unfortunate that the ioctl.h header causes this macro pollution. I'm not sure if there is any better fix than renaming the template argument in HFSM2 or maybe #undef'ing the symbol...

**Comment by andrew-gresyk** [comment]
Thanks for reporting.
I'll rename the arguments to something more obscure.

**Comment by andrew-gresyk** [comment]
@spiderkeys
This should be fixed in https://github.com/andrew-gresyk/HFSM2/releases/tag/1.12.1

**Comment by spiderkeys** [comment]
Hi @andrew-gresyk. I just went to update our HFSM2 to the latest version and it looks like at some point this symbol name switched back from `NCC_` to `NCC`, raising this issue again.

**Comment by andrew-gresyk** [comment]
Thanks for reporting @spiderkeys 
This should be fixed in https://github.com/andrew-gresyk/HFSM2/releases/tag/2.2.2
