### ISSUE TITLE
Multiple copies of same HFSM2 machine

### ISSUE THREAD

**Issue by DonMathi** [andrew-gresyk/HFSM2#7]
Hi Andrew

Do you have some examples on how to make mulitple copies of the same HFSM2 machine?
Creating an object containing an HFSM2, and the creating multiple instances of that obejct

Best regards
Kjeld

**Comment by andrew-gresyk** [comment]
Hi Kjeld,
Do you mean multiple independent instances?

```cpp
	FSM::Instance machine1;
	FSM::Instance machine2;
```
should work, or are you having any specific issues with multiple copies?

Regards,
Andrew

**Comment by DonMathi** [comment]
My challenge was that would like to "hide" the definition of context and structure of the state machine inside a class. I was not able to scope the definition right, to do so.

**Comment by DonMathi** [comment]
So for now I left it outside, and the created instances of the context and machine inside

**Comment by DonMathi** [comment]
My colleague suggested to make a namespace, and wrap the definition inside that. 
I found a link that mention that I can make a [nameless namespace](https://www.internalpointers.com/post/c-namespaces-private-members).

**Comment by andrew-gresyk** [comment]
Right, instead of:

```cpp
#define S(s) struct s

using FSM = M::PeerRoot<
                S(Off),                                // initial top-level state
                M::Composite<S(On),                    // sub-machine region with a head state (On) and and 3 sub-states
                    S(Red),                            // initial sub-state of the region
                    S(Yellow),
                    S(Green)
                >,
                S(Done)
            >;

#undef S
```

try forward declaring the states without a macro, e.g.:

```cpp

struct Off;
struct On;
struct Red;
struct Yellow;
struct Green;
struct Done;

using FSM = M::PeerRoot<
                Off,                                // initial top-level state
                M::Composite<On,                    // sub-machine region with a head state (On) and and 3 sub-states
                    Red,                            // initial sub-state of the region
                    Yellow,
                    Green
                >,
                Done
            >;
```

**Comment by DonMathi** [comment]
Nice that works. Thanks
`#include <hfsm2/machine.hpp>

class TestingHFSM
{
	struct Context
	{
		int value;
	};
	using M = hfsm2::MachineT<hfsm2::Config::ContextT<Context>>;

	struct Begin;
	struct Running;
	struct Stopped;

	using HFSM = M::PeerRoot<
		Begin,
		Running,
		Stopped
	>;

	struct Begin : HFSM::State
	{
		using HFSM::State::react;
	};
	struct Running : HFSM::State
	{
		using HFSM::State::react;
	};
	struct Stopped : HFSM::State
	{
		using HFSM::State::react;
	};

};
`
