### ISSUE TITLE
How get machine state id？

### ISSUE THREAD

**Issue by moonxorsun** [andrew-gresyk/HFSM2#74]
I noticed that `bool isActive(StateID)` API, but not found API that get machine current state id.

**Comment by andrew-gresyk** [comment]
State IDs are 0-based, steadily increasing for every (including empty) state in the hierarchy.

They can be queried using `static StateID stateId<TState>()` function available on all `Root`s, `Control`s and `Plan`s.

[Example](https://github.com/andrew-gresyk/HFSM2/blob/62355d1fa952446690c39feb8875deee81a9b9bb/test/test_internal_transitions.cpp#L65)

**Comment by moonxorsun** [comment]
Thanks for responding so quickly to my request. 

Sorry, i'm not native English, I‘m not sure if I have expressed it correctly.

let's example [basic_audio_player](https://github.com/andrew-gresyk/HFSM2/blob/62355d1fa952446690c39feb8875deee81a9b9bb/examples/basic_audio_player/main.cpp)

```c++
int
main() noexcept {
    // construct everything
    Context title;
    Logger logger;
    FSM::Instance machine(title, &logger);

    // do the work :)
    machine.react(Play{"any"});            // Idle -> Playing
    machine.react(Stop{});                 // Playing -> Idle

    if (machine.isActive<Idle>()) {
        // do something
    } else if (machine.isActive<Playing>()) {
        // do something
    } else if (machine.isActive<Paused>()) {
        // do something
    } else {
        // do something
    }

/*
    switch (machine.current_state_id()) { // my stupid idea
    case FSM::stateId<Idle>(): {
        // do something
        break;
    } case FSM::stateId<Playing>(): {
        // do something
        break;
    } case FSM::stateId<Paused>(): {
        // do something
        break;
    } default:
        // do something
    }
*/

    return 0;
}

```

So, what is  elegant approach that implement `switch (machine.current_state_id())`.

Thanks again,

Kiwi

**Comment by andrew-gresyk** [comment]
1. A *hierarchical* FSM might or might not have *only one* active state. E.g. in [test_internal_transitions](https://github.com/andrew-gresyk/HFSM2/blob/62355d1fa952446690c39feb8875deee81a9b9bb/test/test_internal_transitions.cpp#L42), when `B_1_1` is active, `B` and `B_1_2` are also active.
*Flat* state machines do though, and [FFSM2](https://flat.hfsm.dev/) does have `StateID Root::activeStateId()`.
2. The case you're describing is what we can call 'a passive FSM', i.e. when external-to-FSM code is checking its current configuration and does something based on that (let's call it a *passive* FSM).
Alternatively, I prefer using a different paradigm (*active FSMs*), by moving the logic dependent on which state is active into the state methods.
I.e. the logic from the `if` statement in your example above I'd move into another `react()` method for all relevant states:
```cpp
struct DoMoreWork {}; // new event

struct Idle : Base {
    void react(const DoMoreWork& event, FullControl& control) {
        // do more work here
    }
};

struct Playing : Base {
    void react(const DoMoreWork& event, FullControl& control) {
        // do more work here
    }
};

struct Paused : Base {
    void react(const DoMoreWork& event, FullControl& control) {
        // do more work here
    }
};

int main() {
    // ...

    machine.react(DoMoreWork{}); // more work gets done here
}
```

**Comment by moonxorsun** [comment]
I got it now, thank you
