### ISSUE TITLE
Fetching payload contents

### ISSUE THREAD

**Issue by erem2k** [andrew-gresyk/HFSM2#78]
Hi!
I'm looking to leverage payloads for "messaging" on state switch - both documentation and tests exist for payloads but they don't describe how to actually fetch them.

This was my attempt:
```
void StateActivating::enter(PlanControl& aControl)
{
    auto currentRequest = aControl.requests().begin();

    if (currentRequest != aControl.requests().end() && currentRequest->payloadSet)
    {
        const auto& stateChangePayload = currentRequest->payload();
	// intended entry processing
    }
    else
    {
        // failsafe entry processing
    }
}
```

However `currentRequest != aControl.requests().end()` always evaluates to false, curiously enough `payloadSet` is `true`.

Test code that invokes entry looks like this:
`
fsmInstance.immediateChangeWith<StateActivating>(entryPayload);
`

Perhaps `immediateChangeWith` immediately clears the request? If so, how to retrieve the payload then?

**Comment by erem2k** [comment]
After looking into this further, most of the manipulations on the request list appear to be happening in `R_<TG, TA>::processTransitions`

Contents of `_core.requests` get moved into the reference of `currentTransitions` variable, instance of which itself lives in one level higher in the callstack in `R_<TG, TA>::processRequest`

The move happens before state's enter method is executed, so by the point when in `StateActivating::enter` `aControl.requests()` is invoked the request list is empty.

Is there an alternative way to inspect the current request in state entry? 
`currentTransitions` is used to record state switch history so perhaps enabling it would work as a workaround, but this feels like it needs a more streamlined solution

**Comment by andrew-gresyk** [comment]
Thanks for reporting, @erem2k.

[2.2.3](https://github.com/andrew-gresyk/HFSM2/releases/tag/2.2.3) adds `TPayload* Transition::payload()` accessor for `PlanControl::currentTransitions()`, `GuardControl::pendingTransitions()`, etc.

Please check [`test/test_internal_payloads.cpp`](https://github.com/andrew-gresyk/HFSM2/blob/master/test/test_internal_payloads.cpp) for the usage example.
