### ISSUE TITLE
HFSM2 as parameter in function?

### ISSUE THREAD

**Issue by DonMathi** [andrew-gresyk/HFSM2#8]
Hi Andrew

Thanks for your help last time.
Here comes my next question.
Is it possible to give a hfsm as an parameter in a function?
Could be as a pointer, a reference (or something else, if that is the way to go).

Best regards
Kjeld

**Comment by andrew-gresyk** [comment]
Hi Kjeld,

Could you type in some pseudo-code of what you're trying to achieve?

Regards,
Andrew

**Comment by DonMathi** [comment]
Hi Andrew

I have been busy doing a lot, so I didn't had the time to reply to your question.

What I'm trying to achieve is to have a map of objects, all containing an hfsm2 state machine.
`std::map<uint16_t, actorBase> actorMap;
`
The actors comes in different versions, so I have a actorBase class from which the different actors inherited from.
```
class actorA : public actorBase ...
class actorB : public actorBase ...
```

I have events that know the id and can direct it to the correct actor.
I have defined pure virtual function on the the actorBase
```
virtual void handler(const EventX& e) = 0;
virtual void handler(const EventY& e) = 0;
virtual void handler(const EventZ& e) = 0;
```

And implemented the function in each derived class
```
class actorA : public actorBase
{
void handler(const EventX& e) override {machine.react(e);}
void handler(const EventY& e) override {machine.react(e);}
void handler(const EventZ& e) override {machine.react(e);}
}
```

I was just wondering if it is possible to have the base class to know that there is an machine, and call it with the event directly?

**Comment by andrew-gresyk** [comment]
Hi Kjeld,

```react(TEvent&)``` relies on compile-time (static) polymorphism.

What you want is the run-time (dynamic) polymorphism, which is typically implemented using virtual functions, just like in your example.

The code you show looks like a reasonable implementation for that, at least that's how I would do it.
Maybe with a different hash map, but otherwise, I'd do it the same way.
