### ISSUE TITLE
Conflict with ioctl-types.h

### ISSUE THREAD

**Issue by DonMathi** [andrew-gresyk/HFSM2#9]
Hi Andrew

I found a conflict between your hfsm2.hpp file and ioctl-types.h file
The ioctl-types.h file defines a value for NCC to be 8, and this course your file to make compile errors.
Could you rename your NCC template variable?

```
#define NCC 8
struct termio
  {
    unsigned short int c_iflag;		/* input mode flags */
    unsigned short int c_oflag;		/* output mode flags */
    unsigned short int c_cflag;		/* control mode flags */
    unsigned short int c_lflag;		/* local mode flags */
    unsigned char c_line;		/* line discipline */
    unsigned char c_cc[NCC];		/* control characters */
};
```

**Comment by DonMathi** [comment]
UPS: I mean you machine.hpp file.
My current solution is just to undefine NCC before including machine.hpp

`
#undef NCC
#include "hfsm2/machine.hpp"
`

**Comment by DonMathi** [comment]
NB: ioctl is part of the Linux system
[(http://man7.org/linux/man-pages/man2/ioctl.2.html)]

**Comment by andrew-gresyk** [comment]
Hi Kjeld,

Thanks for reporting this.
I've renamed the template arguments to avoid further compatibility issues.

The changes are available in https://github.com/andrew-gresyk/HFSM2/releases/tag/Beta71
