### ISSUE TITLE
State members?

### ISSUE THREAD

**Issue by chmeeedalf** [andrew-gresyk/HFSM2#93]
This might be a dumb question, but when a state function is called (enter(), update(), etc), is it an instance, with viable member data, or must I call Instance::access<State>() to get access to the current state?

I thought at first that it is an instance, but reading through the source of machine.hpp, it calls Head::enter(), where Head is a type, so I don't see any instance being passed through.

By the way, I love this library.  I looked at the Boost state machine documentation, and couldn't make heads or tails of it reading over for an hour, while I was able to go from zero to skeleton with HFSM2 in less than that time.

For others, I'm using this in an embedded system (RPi Pico, hierarchical states) and it compiles down to a nice size.  I've thus far just tested it in a simulated environment with FreeRTOS (POSIX target), while I work out the rest of the development, but always also compile for my target system as well.

**Comment by andrew-gresyk** [comment]
Non-static state member functions should follow general C++ rules and have access to the current state member variables as normal.

`Instance::access<>()` can indeed be used to access to the current state from outside the FSM.
Similarly, `Control::access<>()` can be used to access any state data from another state's methods.

I might be able to provide better answer if you could posts a minimal relevant example.

Thanks, glad you liked it!

Great to hear it's working well for you on RPi Pico.
Keeping the library embedded-friendly has been a priority in its development.

**Comment by chmeeedalf** [comment]
Thanks, that's what was hoping for!  I have a lot of members in different states, just making sure I'm not clobbering on anything.
