### ISSUE TITLE
Any example about "Hierarchical" ?

### ISSUE THREAD

**Issue by taec1227** [andrew-gresyk/HFSM2#94]
1. Is there any example about how to show a multi-layered fsm (layer number >= 3) ?
2. Any thread-safe feature with the newest version 2.5.0?

**Comment by andrew-gresyk** [comment]
1. Most tests use hierarchy, e.g. [test_internal_transitions.cpp](https://github.com/andrew-gresyk/HFSM2/blob/master/test/test_internal_transitions.cpp)
2. Multi-threading is not directly related to FSMs, can be implemented on the host side, therefore outside the scope for the library

**Comment by taec1227** [comment]
Oh, saw it, thanks.
And another question, is it possible to use the same state in different substates?
e.g.  using FSM = M::PeerRoot<
				M::Composite<S(A),
					S(A_1),
					M::Composite<S(A_2),
						S(A_2_1),
						S(A_2_2)
					>
				>,
				M::Composite<S(B),
					M::Composite<S(B_1),
						S(A_2_1),
						S(A_2_2)
					>
				>
			>; 
Both A and B have A_2_1 and A_2_2.

**Comment by andrew-gresyk** [comment]
There are several options for that:
1. If the states can be exactly the same, they can be made templates with one (possibly non-type) template argument:
`template <int Tag> struct State : M::State {};`
2. Common functionality can be extracted into a base class, and both states inherit from it.
Any base state methods would need to be called manually.
3. Both states can inherit from a common base using `M::StateT<TBase1, TBase2, ...>`
In this case, base state methods will be called by the library, see [test_ancestors.cpp](https://github.com/andrew-gresyk/HFSM2/blob/master/test/test_ancestors.cpp) for example.
